import assert from "node:assert/strict";
import { once } from "node:events";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { chromium } from "playwright";
import { fixtureDigest, syntheticText, pdfFixture, docxFixture } from "./fixtures.mjs";
import { sourceUnits, checkGrounding } from "../lib/source.js";
import { WorkflowError } from "../lib/errors.js";
process.env.SIFT_TEST_MODE = "1";
const { createApp } = await import("../server.js");
const artifacts = new URL("../artifacts/", import.meta.url);
await mkdir(artifacts, { recursive: true });
const modelReport = JSON.parse(await readFile(new URL("model-evaluation.json", artifacts), "utf8"));
const observed = [], failures = [], checks = [];
const app = createApp({ summarize: async input => {
  observed.push(input.sourceType);
  if (input.title === "模拟限流") throw new WorkflowError("模型服务限流，请稍后重试", "MODEL_RATE_LIMITED", 503);
  const unit = sourceUnits(input.text)[0];
  const summary = input.sourceType === "粘贴文本" ? modelReport.cases[0].result.summary : fixtureDigest(unit.locator, unit.text.slice(0, 30), unit.seconds);
  const grounding = checkGrounding(summary, sourceUnits(input.text));
  assert.equal(grounding.valid, true);
  return { summary, sourceExcerpts: grounding.excerpts, grounding: { verifiedQuotes: grounding.quoteCount, totalQuotes: grounding.quoteCount, semanticVerified: false },
    trace: { provider: "fixture", model: "ui-fixture", promptVersion: "grounded-digest-2", chunkCount: 1, calls: [{ status: "passed" }], durationMs: 1, inputTokens: null, outputTokens: null } };
} });
app.listen(0, "127.0.0.1");
await once(app, "listening");
const url = `http://127.0.0.1:${app.address().port}`;
let browser;
try {
  browser = await chromium.launch({ channel: "chrome", headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
  const page = await context.newPage();
  page.on("pageerror", error => failures.push(error.message));
  await page.goto(url);
  await page.locator("#text-tab").click();
  await page.locator("#content-text").fill(syntheticText);
  await page.locator("#text-form button[type=submit]").click();
  await page.locator("#digest").waitFor({ state: "visible" });
  await page.locator(".evidence summary").first().click();
  assert.match(await page.locator(".source-excerpt").first().textContent(), /12 万元/);
  await page.locator(".workflow-trace summary").click();
  const download = page.waitForEvent("download");
  await page.locator("#download-button").click();
  await (await download).saveAs(new URL("ui-export.md", artifacts).pathname);
  assert.match(await readFile(new URL("ui-export.md", artifacts), "utf8"), /12\s*万元|12\s*万元|12 万元/);
  await page.screenshot({ path: new URL("desktop.png", artifacts).pathname, fullPage: true });
  checks.push("desktop text, source excerpt, trace, Markdown download");
  await page.locator("#content-title").fill("模拟限流");
  await page.locator("#text-form button[type=submit]").click();
  await page.waitForFunction(() => document.querySelector("#status").textContent.includes("模型服务限流"));
  assert.equal(await page.locator("#digest").isVisible(), false);
  assert.equal(await page.locator("#text-form button[type=submit]").isDisabled(), false);
  await page.locator("#file-tab").click();
  assert.equal(await page.locator("#file-form button[type=submit]").isDisabled(), true);
  checks.push("typed failure clears stale output and restores valid button state");
  await page.locator("#content-file").setInputFiles({ name: "synthetic.pdf", mimeType: "application/pdf", buffer: pdfFixture(["Internal pilot budget: 120000 CNY for 30 staff, subject to acceptance. Do not release publicly before acceptance."]) });
  await page.locator("#file-form button[type=submit]").click();
  await page.locator("#digest").waitFor({ state: "visible" });
  assert.match(await page.locator(".evidence summary").first().textContent(), /第 1 页/);
  assert.ok(observed.includes("PDF 文件"));
  checks.push("browser PDF.js parsing and page-locator API handoff");
  await page.locator("#content-file").setInputFiles({ name: "synthetic.docx", mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", buffer: docxFixture(syntheticText) });
  await page.locator("#file-form button[type=submit]").click();
  await page.locator("#digest").waitFor({ state: "visible" });
  assert.ok(observed.includes("DOCX 文件"));
  checks.push("Word multipart upload and parsing");
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator("#text-tab").click();
  await page.locator("#content-title").fill("合成试点");
  await page.locator("#text-form button[type=submit]").click();
  await page.locator("#digest").waitFor({ state: "visible" });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  await page.screenshot({ path: new URL("mobile.png", artifacts).pathname, fullPage: true });
  assert.deepEqual(failures, []);
  checks.push("390px mobile rendering without horizontal overflow or JS errors");
  await writeFile(new URL("ui-validation.json", artifacts), JSON.stringify({ passed: true, model: "injected fixture; no API calls", checks }, null, 2));
  console.log(JSON.stringify({ passed: true, checks }, null, 2));
} finally {
  await browser?.close();
  await new Promise(resolve => { app.close(resolve); app.closeAllConnections(); });
}
